/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_signup (void);
GtkWidget* create_DashAdmin (void);
GtkWidget* create_DashMembre (void);
GtkWidget* create_DashEntraineur (void);
GtkWidget* create_Gestion_membre_Admin (void);
GtkWidget* create_Gestion_Membre_Membre (void);
GtkWidget* create_Gestion_entraineurs_Admin (void);
GtkWidget* create_Gestions_des_Cours_sportifs_Admin (void);
GtkWidget* create_Gestion_des_equippements_Admin (void);
GtkWidget* create_Gestion_des_Centres_Sportifs_Admin (void);
GtkWidget* create_Gestion_des_evenements_Admin (void);
GtkWidget* create_Espace_entraineur_entraineur (void);
GtkWidget* create_Cours_sportifs__membre (void);
GtkWidget* create_Equippements_entraineurs (void);
GtkWidget* create_Centre_entraineurs (void);
GtkWidget* create_Evenements_membre (void);
GtkWidget* create_window_login (void);
GtkWidget* create_window_choix (void);
