/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"
#include "callbacks.h"

GtkBuilder *builder;

int main (int argc, char *argv[])
{
  GtkWidget *window_choix;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */

  // 1. Créer le builder
  builder = gtk_builder_new();
  
  // 2. Charger le fichier .glade
  if (!gtk_builder_add_from_file(builder, "interface.glade", NULL)) {
    g_print("Erreur: Impossible de charger interface.glade\n");
    return 1;
  }
  
  // 3. Initialiser support
  support_init(builder);
  
  // 4. CONNECTER LES SIGNALS (CALLBACKS) - IMPORTANT !
  gtk_builder_connect_signals(builder, NULL);
  
  // 5. Obtenir window_choix depuis le builder
  window_choix = GTK_WIDGET(gtk_builder_get_object(builder, "window_choix"));
  
  if (!window_choix) {
    g_print("Erreur: window_choix non trouvée dans le fichier .glade\n");
    // Option: lister tous les objets disponibles pour déboguer
    // GList *objects = gtk_builder_get_objects(builder);
    // while (objects) {
    //   g_print("Objet: %s\n", G_OBJECT_TYPE_NAME(objects->data));
    //   objects = objects->next;
    // }
    return 1;
  }
  
  // 6. Afficher window_choix
  gtk_widget_show_all(window_choix);
 
  gtk_main ();
  
  // 7. Nettoyer
  g_object_unref(G_OBJECT(builder));
  return 0;
}
