/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *button1;
  GtkWidget *Label;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (login), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 232, 144);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed1), entry2, 232, 184);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  label2 = gtk_label_new (_("Login:"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 104, 144);
  gtk_widget_set_size_request (label2, 88, 24);

  label3 = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 72, 184);
  gtk_widget_set_size_request (label3, 113, 16);

  button1 = gtk_button_new_with_mnemonic (_("Se Connecter"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 168, 240);
  gtk_widget_set_size_request (button1, 120, 29);

  Label = gtk_label_new (_("Connexion"));
  gtk_widget_show (Label);
  gtk_fixed_put (GTK_FIXED (fixed1), Label, 136, 80);
  gtk_widget_set_size_request (Label, 184, 40);
  gtk_misc_set_alignment (GTK_MISC (Label), 0.57, 0.67);
  gtk_misc_set_padding (GTK_MISC (Label), 1, 8);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (login, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (login, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (login, label2, "label2");
  GLADE_HOOKUP_OBJECT (login, label3, "label3");
  GLADE_HOOKUP_OBJECT (login, button1, "button1");
  GLADE_HOOKUP_OBJECT (login, Label, "Label");

  return login;
}

GtkWidget*
create_Dash_Admin (void)
{
  GtkWidget *Dash_Admin;
  GtkWidget *fixed2;
  GtkWidget *button3;
  GtkWidget *label4;
  GtkWidget *button2;
  GtkWidget *button5;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button4;
  GtkWidget *button6;

  Dash_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Dash_Admin), _("Dash Admin"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Dash_Admin), fixed2);

  button3 = gtk_button_new_with_mnemonic (_("Gestion des entraineurs"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed2), button3, 112, 168);
  gtk_widget_set_size_request (button3, 192, 32);

  label4 = gtk_label_new (_("Dashboard Administrateur"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 40, 72);
  gtk_widget_set_size_request (label4, 336, 32);

  button2 = gtk_button_new_with_mnemonic (_("Gestion des membres"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed2), button2, 112, 128);
  gtk_widget_set_size_request (button2, 192, 32);

  button5 = gtk_button_new_with_mnemonic (_("Gestions des equipements"));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed2), button5, 112, 248);
  gtk_widget_set_size_request (button5, 192, 32);

  button7 = gtk_button_new_with_mnemonic (_("Gestions des evenements"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed2), button7, 112, 328);
  gtk_widget_set_size_request (button7, 192, 32);

  button8 = gtk_button_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed2), button8, 136, 376);
  gtk_widget_set_size_request (button8, 152, 32);

  button4 = gtk_button_new_with_mnemonic (_("Gestion des Cours Sportifs"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed2), button4, 112, 208);
  gtk_widget_set_size_request (button4, 192, 32);

  button6 = gtk_button_new_with_mnemonic (_("Gestions des centres sportifs"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed2), button6, 112, 288);
  gtk_widget_set_size_request (button6, 192, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Dash_Admin, Dash_Admin, "Dash_Admin");
  GLADE_HOOKUP_OBJECT (Dash_Admin, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button3, "button3");
  GLADE_HOOKUP_OBJECT (Dash_Admin, label4, "label4");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button2, "button2");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button5, "button5");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button7, "button7");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button8, "button8");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button4, "button4");
  GLADE_HOOKUP_OBJECT (Dash_Admin, button6, "button6");

  return Dash_Admin;
}

GtkWidget*
create_Dash_Membre (void)
{
  GtkWidget *Dash_Membre;
  GtkWidget *fixed3;
  GtkWidget *ss;
  GtkWidget *button10;
  GtkWidget *button12;
  GtkWidget *button11;
  GtkWidget *button13;

  Dash_Membre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Dash_Membre), _("window2"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Dash_Membre), fixed3);

  ss = gtk_label_new (_("Dashboard Membre"));
  gtk_widget_show (ss);
  gtk_fixed_put (GTK_FIXED (fixed3), ss, 96, 33);
  gtk_widget_set_size_request (ss, 216, 31);

  button10 = gtk_button_new_with_mnemonic (_("S'inscrire a un cours"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed3), button10, 112, 120);
  gtk_widget_set_size_request (button10, 184, 24);

  button12 = gtk_button_new_with_mnemonic (_("Demander un coach"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed3), button12, 112, 152);
  gtk_widget_set_size_request (button12, 184, 24);

  button11 = gtk_button_new_with_mnemonic (_("S'inscrire a un evenement"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed3), button11, 112, 184);
  gtk_widget_set_size_request (button11, 186, 32);

  button13 = gtk_button_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed3), button13, 112, 224);
  gtk_widget_set_size_request (button13, 184, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Dash_Membre, Dash_Membre, "Dash_Membre");
  GLADE_HOOKUP_OBJECT (Dash_Membre, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Dash_Membre, ss, "ss");
  GLADE_HOOKUP_OBJECT (Dash_Membre, button10, "button10");
  GLADE_HOOKUP_OBJECT (Dash_Membre, button12, "button12");
  GLADE_HOOKUP_OBJECT (Dash_Membre, button11, "button11");
  GLADE_HOOKUP_OBJECT (Dash_Membre, button13, "button13");

  return Dash_Membre;
}

GtkWidget*
create_Dash_Entraineur (void)
{
  GtkWidget *Dash_Entraineur;
  GtkWidget *fixed4;
  GtkWidget *button15;
  GtkWidget *button14;
  GtkWidget *label6;
  GtkWidget *button17;
  GtkWidget *button16;

  Dash_Entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Dash_Entraineur), _("window3"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Dash_Entraineur), fixed4);

  button15 = gtk_button_new_with_mnemonic (_("Reserver equipements"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed4), button15, 120, 136);
  gtk_widget_set_size_request (button15, 162, 32);

  button14 = gtk_button_new_with_mnemonic (_("Rejoindre un cours"));
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed4), button14, 120, 96);
  gtk_widget_set_size_request (button14, 160, 32);

  label6 = gtk_label_new (_("Dashboard Entraineur"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed4), label6, 96, 40);
  gtk_widget_set_size_request (label6, 208, 40);

  button17 = gtk_button_new_with_mnemonic (_("Deconnexion"));
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed4), button17, 136, 216);
  gtk_widget_set_size_request (button17, 130, 24);

  button16 = gtk_button_new_with_mnemonic (_("Postuler a un centre"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed4), button16, 120, 176);
  gtk_widget_set_size_request (button16, 160, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Dash_Entraineur, Dash_Entraineur, "Dash_Entraineur");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, button15, "button15");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, button14, "button14");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, label6, "label6");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, button17, "button17");
  GLADE_HOOKUP_OBJECT (Dash_Entraineur, button16, "button16");

  return Dash_Entraineur;
}

GtkWidget*
create_Gestion_membre_Admin (void)
{
  GtkWidget *Gestion_membre_Admin;
  GtkWidget *fixed5;
  GtkWidget *entry3;
  GtkWidget *button18;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label16;
  GtkWidget *label15;
  GtkWidget *comboboxentry3;
  GtkWidget *comboboxentry4;
  GtkWidget *comboboxentry5;
  GtkWidget *treeview1;
  GtkWidget *button19;
  GtkWidget *button20;
  GtkWidget *button21;
  GtkWidget *label14;

  Gestion_membre_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_membre_Admin), _("window4"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Gestion_membre_Admin), fixed5);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 128, 96);
  gtk_widget_set_size_request (entry3, 176, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  button18 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed5), button18, 312, 96);
  gtk_widget_set_size_request (button18, 96, 29);

  label17 = gtk_label_new (_("Statut:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed5), label17, 32, 176);
  gtk_widget_set_size_request (label17, 80, 25);

  label18 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed5), label18, 40, 216);
  gtk_widget_set_size_request (label18, 65, 24);

  label16 = gtk_label_new (_("Centre:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed5), label16, 32, 136);
  gtk_widget_set_size_request (label16, 73, 24);

  label15 = gtk_label_new (_("Rechercher:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed5), label15, 16, 96);
  gtk_widget_set_size_request (label15, 112, 25);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry3, 128, 136);
  gtk_widget_set_size_request (comboboxentry3, 181, 29);

  comboboxentry4 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry4);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry4, 128, 176);
  gtk_widget_set_size_request (comboboxentry4, 181, 29);

  comboboxentry5 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry5);
  gtk_fixed_put (GTK_FIXED (fixed5), comboboxentry5, 128, 216);
  gtk_widget_set_size_request (comboboxentry5, 181, 29);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 48, 256);
  gtk_widget_set_size_request (treeview1, 376, 120);

  button19 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button19);
  gtk_fixed_put (GTK_FIXED (fixed5), button19, 72, 400);
  gtk_widget_set_size_request (button19, 80, 32);

  button20 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button20);
  gtk_fixed_put (GTK_FIXED (fixed5), button20, 208, 400);
  gtk_widget_set_size_request (button20, 80, 32);

  button21 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button21);
  gtk_fixed_put (GTK_FIXED (fixed5), button21, 336, 400);
  gtk_widget_set_size_request (button21, 96, 32);

  label14 = gtk_label_new (_("Gestion des membres-Admin"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed5), label14, 104, 32);
  gtk_widget_set_size_request (label14, 264, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_membre_Admin, Gestion_membre_Admin, "Gestion_membre_Admin");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, button18, "button18");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, label17, "label17");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, label18, "label18");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, label15, "label15");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, comboboxentry4, "comboboxentry4");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, comboboxentry5, "comboboxentry5");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, button19, "button19");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, button20, "button20");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, button21, "button21");
  GLADE_HOOKUP_OBJECT (Gestion_membre_Admin, label14, "label14");

  return Gestion_membre_Admin;
}

GtkWidget*
create_Gestion_Membre_Membre (void)
{
  GtkWidget *Gestion_Membre_Membre;
  GtkWidget *fixed6;
  GtkWidget *entry4;
  GtkWidget *calendar1;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *comboboxentry7;
  GtkWidget *comboboxentry6;
  GtkWidget *comboboxentry8;
  GtkWidget *comboboxentry9;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *comboboxentry10;
  GtkWidget *entry7;
  GtkWidget *button24;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label22;
  GtkWidget *label25;
  GtkWidget *button22;
  GtkWidget *button23;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label21;

  Gestion_Membre_Membre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_Membre_Membre), _("window5"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Gestion_Membre_Membre), fixed6);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 200, 120);
  gtk_widget_set_size_request (entry4, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  calendar1 = gtk_calendar_new ();
  gtk_widget_show (calendar1);
  gtk_fixed_put (GTK_FIXED (fixed6), calendar1, 200, 160);
  gtk_widget_set_size_request (calendar1, 176, 32);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_WEEK_START_MONDAY);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 200, 200);
  gtk_widget_set_size_request (entry5, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed6), entry6, 200, 240);
  gtk_widget_set_size_request (entry6, 176, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  comboboxentry7 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry7);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry7, 200, 328);
  gtk_widget_set_size_request (comboboxentry7, 181, 32);

  comboboxentry6 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry6);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry6, 200, 280);
  gtk_widget_set_size_request (comboboxentry6, 181, 32);

  comboboxentry8 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry8);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry8, 192, 544);
  gtk_widget_set_size_request (comboboxentry8, 189, 29);

  comboboxentry9 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry9);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry9, 192, 592);
  gtk_widget_set_size_request (comboboxentry9, 189, 29);

  label23 = gtk_label_new (_("Email:"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed6), label23, 48, 240);
  gtk_widget_set_size_request (label23, 120, 32);

  label24 = gtk_label_new (_("Centre:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed6), label24, 56, 280);
  gtk_widget_set_size_request (label24, 104, 32);

  comboboxentry10 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry10);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry10, 192, 640);
  gtk_widget_set_size_request (comboboxentry10, 189, 29);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed6), entry7, 192, 688);
  gtk_widget_set_size_request (entry7, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  button24 = gtk_button_new_with_mnemonic (_("Envoyer la demande"));
  gtk_widget_show (button24);
  gtk_fixed_put (GTK_FIXED (fixed6), button24, 136, 736);
  gtk_widget_set_size_request (button24, 298, 48);

  label19 = gtk_label_new (_("Mon Profil - Membre"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 96, 48);
  gtk_widget_set_size_request (label19, 304, 40);

  label20 = gtk_label_new (_("Nom et Prenom:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 40, 120);
  gtk_widget_set_size_request (label20, 144, 32);

  label22 = gtk_label_new (_("Telephone:"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 32, 200);
  gtk_widget_set_size_request (label22, 144, 32);

  label25 = gtk_label_new (_("Statut:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed6), label25, 56, 328);
  gtk_widget_set_size_request (label25, 104, 32);

  button22 = gtk_button_new_with_mnemonic (_("Modifier mes infos"));
  gtk_widget_show (button22);
  gtk_fixed_put (GTK_FIXED (fixed6), button22, 40, 408);
  gtk_widget_set_size_request (button22, 216, 40);

  button23 = gtk_button_new_with_mnemonic (_("changer mot de passe"));
  gtk_widget_show (button23);
  gtk_fixed_put (GTK_FIXED (fixed6), button23, 280, 408);
  gtk_widget_set_size_request (button23, 208, 40);

  label26 = gtk_label_new (_("Demander un Coach"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed6), label26, 136, 472);
  gtk_widget_set_size_request (label26, 232, 40);

  label27 = gtk_label_new (_("Specialite:"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed6), label27, 64, 544);
  gtk_widget_set_size_request (label27, 105, 32);

  label28 = gtk_label_new (_("Disponibilite:"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed6), label28, 64, 592);
  gtk_widget_set_size_request (label28, 105, 24);

  label29 = gtk_label_new (_("Frequence:"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed6), label29, 72, 640);
  gtk_widget_set_size_request (label29, 97, 24);

  label30 = gtk_label_new (_("Message:"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed6), label30, 64, 688);
  gtk_widget_set_size_request (label30, 104, 24);

  label21 = gtk_label_new (_("Date de Naissance:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed6), label21, 32, 160);
  gtk_widget_set_size_request (label21, 152, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_Membre_Membre, Gestion_Membre_Membre, "Gestion_Membre_Membre");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, calendar1, "calendar1");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, comboboxentry7, "comboboxentry7");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, comboboxentry6, "comboboxentry6");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, comboboxentry8, "comboboxentry8");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, comboboxentry9, "comboboxentry9");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label23, "label23");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label24, "label24");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, comboboxentry10, "comboboxentry10");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, button24, "button24");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label19, "label19");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label20, "label20");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label22, "label22");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label25, "label25");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, button22, "button22");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, button23, "button23");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label26, "label26");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label27, "label27");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label28, "label28");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label29, "label29");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label30, "label30");
  GLADE_HOOKUP_OBJECT (Gestion_Membre_Membre, label21, "label21");

  return Gestion_Membre_Membre;
}

GtkWidget*
create_Gestion_entraineurs_Admin (void)
{
  GtkWidget *Gestion_entraineurs_Admin;
  GtkWidget *fixed7;
  GtkWidget *label31;
  GtkWidget *entry8;
  GtkWidget *label32;
  GtkWidget *button25;
  GtkWidget *treeview2;
  GtkWidget *label73;
  GtkWidget *entry25;
  GtkWidget *label74;
  GtkWidget *comboboxentry21;
  GtkWidget *label75;
  GtkWidget *entry26;
  GtkWidget *label76;
  GtkWidget *entry27;
  GtkWidget *radiobutton4;
  GSList *radiobutton4_group = NULL;
  GtkWidget *label77;
  GtkWidget *radiobutton5;
  GtkWidget *button26;
  GtkWidget *button27;
  GtkWidget *button28;

  Gestion_entraineurs_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_entraineurs_Admin), _("window6"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Gestion_entraineurs_Admin), fixed7);

  label31 = gtk_label_new (_("Gestion des entraineurs-Admin"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 56, 32);
  gtk_widget_set_size_request (label31, 264, 32);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed7), entry8, 120, 96);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label32 = gtk_label_new (_("Rechercher:"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 8, 88);
  gtk_widget_set_size_request (label32, 120, 40);

  button25 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button25);
  gtk_fixed_put (GTK_FIXED (fixed7), button25, 296, 96);
  gtk_widget_set_size_request (button25, 98, 29);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview2, 48, 136);
  gtk_widget_set_size_request (treeview2, 336, 120);

  label73 = gtk_label_new (_("Nom et Prenom:"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed7), label73, 0, 288);
  gtk_widget_set_size_request (label73, 136, 24);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed7), entry25, 128, 288);
  gtk_widget_set_size_request (entry25, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  label74 = gtk_label_new (_("Specialite:"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed7), label74, 16, 328);
  gtk_widget_set_size_request (label74, 112, 24);

  comboboxentry21 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry21);
  gtk_fixed_put (GTK_FIXED (fixed7), comboboxentry21, 128, 328);
  gtk_widget_set_size_request (comboboxentry21, 165, 29);

  label75 = gtk_label_new (_("Telephone:"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed7), label75, 24, 368);
  gtk_widget_set_size_request (label75, 96, 24);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed7), entry26, 136, 368);
  gtk_widget_set_size_request (entry26, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  label76 = gtk_label_new (_("Email:"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed7), label76, 32, 408);
  gtk_widget_set_size_request (label76, 88, 16);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed7), entry27, 136, 408);
  gtk_widget_set_size_request (entry27, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  radiobutton4 = gtk_radio_button_new_with_mnemonic (NULL, _("Actif"));
  gtk_widget_show (radiobutton4);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton4, 128, 448);
  gtk_widget_set_size_request (radiobutton4, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4));

  label77 = gtk_label_new (_("Statut:"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed7), label77, 40, 448);
  gtk_widget_set_size_request (label77, 72, 24);

  radiobutton5 = gtk_radio_button_new_with_mnemonic (NULL, _("Inactive"));
  gtk_widget_show (radiobutton5);
  gtk_fixed_put (GTK_FIXED (fixed7), radiobutton5, 240, 448);
  gtk_widget_set_size_request (radiobutton5, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5), radiobutton4_group);
  radiobutton4_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5));

  button26 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button26);
  gtk_fixed_put (GTK_FIXED (fixed7), button26, 80, 496);
  gtk_widget_set_size_request (button26, 74, 29);

  button27 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button27);
  gtk_fixed_put (GTK_FIXED (fixed7), button27, 184, 496);
  gtk_widget_set_size_request (button27, 74, 29);

  button28 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button28);
  gtk_fixed_put (GTK_FIXED (fixed7), button28, 280, 496);
  gtk_widget_set_size_request (button28, 96, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_entraineurs_Admin, Gestion_entraineurs_Admin, "Gestion_entraineurs_Admin");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label31, "label31");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label32, "label32");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, button25, "button25");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label73, "label73");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label74, "label74");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, comboboxentry21, "comboboxentry21");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label75, "label75");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label76, "label76");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, radiobutton4, "radiobutton4");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, label77, "label77");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, radiobutton5, "radiobutton5");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, button26, "button26");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, button27, "button27");
  GLADE_HOOKUP_OBJECT (Gestion_entraineurs_Admin, button28, "button28");

  return Gestion_entraineurs_Admin;
}

GtkWidget*
create_Gestions_des_Cours_sportifs_Admin (void)
{
  GtkWidget *Gestions_des_Cours_sportifs_Admin;
  GtkWidget *fixed9;
  GtkWidget *label39;
  GtkWidget *entry12;
  GtkWidget *label40;
  GtkWidget *treeview3;
  GtkWidget *button31;
  GtkWidget *label41;
  GtkWidget *entry13;
  GtkWidget *comboboxentry13;
  GtkWidget *label42;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *label46;
  GtkWidget *comboboxentry14;
  GtkWidget *label47;
  GtkWidget *comboboxentry15;
  GtkWidget *button34;
  GtkWidget *button35;
  GtkWidget *button33;
  GtkWidget *button32;

  Gestions_des_Cours_sportifs_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestions_des_Cours_sportifs_Admin), _("window8"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (Gestions_des_Cours_sportifs_Admin), fixed9);

  label39 = gtk_label_new (_("Gestion des Cours sportifs"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed9), label39, 112, 40);
  gtk_widget_set_size_request (label39, 272, 48);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed9), entry12, 144, 120);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  label40 = gtk_label_new (_("Recherche:"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed9), label40, 24, 112);
  gtk_widget_set_size_request (label40, 128, 40);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview3, 40, 184);
  gtk_widget_set_size_request (treeview3, 440, 96);

  button31 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button31);
  gtk_fixed_put (GTK_FIXED (fixed9), button31, 344, 120);
  gtk_widget_set_size_request (button31, 104, 29);

  label41 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed9), label41, 56, 304);
  gtk_widget_set_size_request (label41, 81, 24);

  entry13 = gtk_entry_new ();
  gtk_widget_show (entry13);
  gtk_fixed_put (GTK_FIXED (fixed9), entry13, 144, 304);
  gtk_widget_set_size_request (entry13, 168, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry13), 8226);

  comboboxentry13 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry13);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry13, 144, 344);
  gtk_widget_set_size_request (comboboxentry13, 173, 29);

  label42 = gtk_label_new (_("Type:"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed9), label42, 64, 344);
  gtk_widget_set_size_request (label42, 65, 24);

  spinbutton1_adj = gtk_adjustment_new (26, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton1, 144, 384);
  gtk_widget_set_size_request (spinbutton1, 72, 24);

  spinbutton2_adj = gtk_adjustment_new (5, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton2, 216, 384);
  gtk_widget_set_size_request (spinbutton2, 60, 24);

  spinbutton3_adj = gtk_adjustment_new (100, 0, 100, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton3, 280, 384);
  gtk_widget_set_size_request (spinbutton3, 60, 24);

  spinbutton4_adj = gtk_adjustment_new (12, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton4, 160, 424);
  gtk_widget_set_size_request (spinbutton4, 80, 24);

  label43 = gtk_label_new (_("Date:"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed9), label43, 72, 384);
  gtk_widget_set_size_request (label43, 56, 25);

  label44 = gtk_label_new (_("Horaire:"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed9), label44, 56, 424);
  gtk_widget_set_size_request (label44, 72, 25);

  label45 = gtk_label_new (_("Place:"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed9), label45, 64, 464);
  gtk_widget_set_size_request (label45, 65, 24);

  spinbutton5_adj = gtk_adjustment_new (20, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed9), spinbutton5, 160, 464);
  gtk_widget_set_size_request (spinbutton5, 80, 24);

  label46 = gtk_label_new (_("Salle:"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed9), label46, 64, 504);
  gtk_widget_set_size_request (label46, 65, 24);

  comboboxentry14 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry14);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry14, 160, 504);
  gtk_widget_set_size_request (comboboxentry14, 189, 29);

  label47 = gtk_label_new (_("Entraineurs:"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed9), label47, 48, 552);
  gtk_widget_set_size_request (label47, 89, 24);

  comboboxentry15 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry15);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentry15, 160, 552);
  gtk_widget_set_size_request (comboboxentry15, 189, 29);

  button34 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button34);
  gtk_fixed_put (GTK_FIXED (fixed9), button34, 296, 608);
  gtk_widget_set_size_request (button34, 88, 32);

  button35 = gtk_button_new_with_mnemonic (_("Vider"));
  gtk_widget_show (button35);
  gtk_fixed_put (GTK_FIXED (fixed9), button35, 408, 608);
  gtk_widget_set_size_request (button35, 88, 32);

  button33 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button33);
  gtk_fixed_put (GTK_FIXED (fixed9), button33, 184, 608);
  gtk_widget_set_size_request (button33, 80, 32);

  button32 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button32);
  gtk_fixed_put (GTK_FIXED (fixed9), button32, 80, 608);
  gtk_widget_set_size_request (button32, 80, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestions_des_Cours_sportifs_Admin, Gestions_des_Cours_sportifs_Admin, "Gestions_des_Cours_sportifs_Admin");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label39, "label39");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label40, "label40");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, button31, "button31");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, entry13, "entry13");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, comboboxentry13, "comboboxentry13");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label42, "label42");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label44, "label44");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label45, "label45");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label46, "label46");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, comboboxentry14, "comboboxentry14");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, label47, "label47");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, comboboxentry15, "comboboxentry15");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, button34, "button34");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, button35, "button35");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, button33, "button33");
  GLADE_HOOKUP_OBJECT (Gestions_des_Cours_sportifs_Admin, button32, "button32");

  return Gestions_des_Cours_sportifs_Admin;
}

GtkWidget*
create_Gestion_des_equippements_Admin (void)
{
  GtkWidget *Gestion_des_equippements_Admin;
  GtkWidget *fixed10;
  GtkWidget *label49;
  GtkWidget *entry14;
  GtkWidget *button36;
  GtkWidget *treeview4;
  GtkWidget *entry15;
  GtkWidget *label50;
  GtkWidget *comboboxentry16;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *comboboxentry17;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *label53;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label54;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkWidget *button39;
  GtkWidget *button37;
  GtkWidget *button38;
  GtkWidget *label48;
  GtkWidget *radiobutton2;
  GtkWidget *radiobutton3;

  Gestion_des_equippements_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_equippements_Admin), _("window9"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (Gestion_des_equippements_Admin), fixed10);

  label49 = gtk_label_new (_("Recherche:"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed10), label49, 48, 112);
  gtk_widget_set_size_request (label49, 104, 24);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed10), entry14, 152, 112);
  gtk_widget_set_size_request (entry14, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  button36 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button36);
  gtk_fixed_put (GTK_FIXED (fixed10), button36, 344, 112);
  gtk_widget_set_size_request (button36, 96, 29);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed10), treeview4, 72, 160);
  gtk_widget_set_size_request (treeview4, 344, 96);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed10), entry15, 160, 272);
  gtk_widget_set_size_request (entry15, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  label50 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed10), label50, 72, 272);
  gtk_widget_set_size_request (label50, 72, 24);

  comboboxentry16 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry16);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry16, 160, 304);
  gtk_widget_set_size_request (comboboxentry16, 165, 29);

  label51 = gtk_label_new (_("Type:"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed10), label51, 80, 304);
  gtk_widget_set_size_request (label51, 64, 24);

  label52 = gtk_label_new (_("Salle:"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed10), label52, 80, 336);
  gtk_widget_set_size_request (label52, 73, 25);

  comboboxentry17 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry17);
  gtk_fixed_put (GTK_FIXED (fixed10), comboboxentry17, 160, 336);
  gtk_widget_set_size_request (comboboxentry17, 165, 29);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Libre"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton1, 168, 376);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label53 = gtk_label_new (_("Statut:"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed10), label53, 72, 376);
  gtk_widget_set_size_request (label53, 80, 24);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton6, 168, 424);
  gtk_widget_set_size_request (spinbutton6, 64, 24);

  label54 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed10), label54, 16, 416);
  gtk_widget_set_size_request (label54, 144, 32);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton7, 232, 424);
  gtk_widget_set_size_request (spinbutton7, 56, 24);

  spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton8, 288, 424);
  gtk_widget_set_size_request (spinbutton8, 56, 24);

  button39 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button39);
  gtk_fixed_put (GTK_FIXED (fixed10), button39, 352, 472);
  gtk_widget_set_size_request (button39, 88, 29);

  button37 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button37);
  gtk_fixed_put (GTK_FIXED (fixed10), button37, 104, 472);
  gtk_widget_set_size_request (button37, 74, 29);

  button38 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button38);
  gtk_fixed_put (GTK_FIXED (fixed10), button38, 240, 472);
  gtk_widget_set_size_request (button38, 74, 29);

  label48 = gtk_label_new (_("Gestion des equipements"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed10), label48, 160, 40);
  gtk_widget_set_size_request (label48, 208, 48);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Reserve"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton2, 256, 376);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton3 = gtk_radio_button_new_with_mnemonic (NULL, _("Maintenance"));
  gtk_widget_show (radiobutton3);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton3, 368, 376);
  gtk_widget_set_size_request (radiobutton3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_equippements_Admin, Gestion_des_equippements_Admin, "Gestion_des_equippements_Admin");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label49, "label49");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, button36, "button36");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label50, "label50");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, comboboxentry16, "comboboxentry16");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label51, "label51");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label52, "label52");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, comboboxentry17, "comboboxentry17");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label53, "label53");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label54, "label54");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, button39, "button39");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, button37, "button37");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, button38, "button38");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, label48, "label48");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Gestion_des_equippements_Admin, radiobutton3, "radiobutton3");

  return Gestion_des_equippements_Admin;
}

GtkWidget*
create_Gestion_des_Centres_Sportifs_Admin (void)
{
  GtkWidget *Gestion_des_Centres_Sportifs_Admin;
  GtkWidget *fixed11;
  GtkWidget *entry16;
  GtkWidget *treeview5;
  GtkWidget *button40;
  GtkWidget *label56;
  GtkWidget *label55;
  GtkWidget *label57;
  GtkWidget *entry17;
  GtkWidget *label58;
  GtkWidget *entry18;
  GtkWidget *label59;
  GtkWidget *entry19;
  GtkWidget *entry20;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *entry21;
  GtkWidget *label62;
  GtkWidget *button43;
  GtkWidget *button41;
  GtkWidget *button42;

  Gestion_des_Centres_Sportifs_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_Centres_Sportifs_Admin), _("window10"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (Gestion_des_Centres_Sportifs_Admin), fixed11);

  entry16 = gtk_entry_new ();
  gtk_widget_show (entry16);
  gtk_fixed_put (GTK_FIXED (fixed11), entry16, 112, 104);
  gtk_widget_set_size_request (entry16, 184, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry16), 8226);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview5, 48, 160);
  gtk_widget_set_size_request (treeview5, 352, 96);

  button40 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button40);
  gtk_fixed_put (GTK_FIXED (fixed11), button40, 312, 104);
  gtk_widget_set_size_request (button40, 114, 29);

  label56 = gtk_label_new (_("Recherche:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 0, 104);
  gtk_widget_set_size_request (label56, 104, 32);

  label55 = gtk_label_new (_("Gestions des centres sportifs-Admin"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 56, 40);
  gtk_widget_set_size_request (label55, 320, 40);

  label57 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 16, 272);
  gtk_widget_set_size_request (label57, 80, 24);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed11), entry17, 120, 272);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  label58 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed11), label58, 16, 312);
  gtk_widget_set_size_request (label58, 80, 24);

  entry18 = gtk_entry_new ();
  gtk_widget_show (entry18);
  gtk_fixed_put (GTK_FIXED (fixed11), entry18, 120, 312);
  gtk_widget_set_size_request (entry18, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry18), 8226);

  label59 = gtk_label_new (_("Ville:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed11), label59, 8, 352);
  gtk_widget_set_size_request (label59, 88, 24);

  entry19 = gtk_entry_new ();
  gtk_widget_show (entry19);
  gtk_fixed_put (GTK_FIXED (fixed11), entry19, 120, 352);
  gtk_widget_set_size_request (entry19, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry19), 8226);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed11), entry20, 120, 392);
  gtk_widget_set_size_request (entry20, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label60 = gtk_label_new (_("Telephone:"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed11), label60, 8, 392);
  gtk_widget_set_size_request (label60, 96, 24);

  label61 = gtk_label_new (_("Capacite:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed11), label61, 8, 432);
  gtk_widget_set_size_request (label61, 88, 24);

  spinbutton9_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed11), spinbutton9, 120, 432);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed11), entry21, 120, 472);
  gtk_widget_set_size_request (entry21, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  label62 = gtk_label_new (_("Horaires:"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed11), label62, 16, 472);
  gtk_widget_set_size_request (label62, 72, 24);

  button43 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button43);
  gtk_fixed_put (GTK_FIXED (fixed11), button43, 296, 536);
  gtk_widget_set_size_request (button43, 96, 32);

  button41 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button41);
  gtk_fixed_put (GTK_FIXED (fixed11), button41, 64, 536);
  gtk_widget_set_size_request (button41, 88, 32);

  button42 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button42);
  gtk_fixed_put (GTK_FIXED (fixed11), button42, 184, 536);
  gtk_widget_set_size_request (button42, 90, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_Centres_Sportifs_Admin, Gestion_des_Centres_Sportifs_Admin, "Gestion_des_Centres_Sportifs_Admin");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry16, "entry16");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, button40, "button40");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label56, "label56");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label55, "label55");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label57, "label57");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label58, "label58");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry18, "entry18");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label59, "label59");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry19, "entry19");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label60, "label60");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label61, "label61");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, label62, "label62");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, button43, "button43");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, button41, "button41");
  GLADE_HOOKUP_OBJECT (Gestion_des_Centres_Sportifs_Admin, button42, "button42");

  return Gestion_des_Centres_Sportifs_Admin;
}

GtkWidget*
create_Gestion_des_evenements_Admin (void)
{
  GtkWidget *Gestion_des_evenements_Admin;
  GtkWidget *fixed12;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *entry22;
  GtkWidget *button44;
  GtkWidget *treeview6;
  GtkWidget *entry23;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *comboboxentry18;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *label67;
  GtkWidget *label68;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkWidget *label69;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkWidget *label70;
  GtkWidget *comboboxentry19;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *entry24;
  GtkWidget *comboboxentry20;
  GtkWidget *button47;
  GtkWidget *button46;
  GtkWidget *button45;

  Gestion_des_evenements_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_des_evenements_Admin), _("window11"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (Gestion_des_evenements_Admin), fixed12);

  label63 = gtk_label_new (_("Gestion des evenements-Admin"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed12), label63, 80, 16);
  gtk_widget_set_size_request (label63, 240, 56);

  label64 = gtk_label_new (_("Recherche:"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed12), label64, 16, 72);
  gtk_widget_set_size_request (label64, 96, 24);

  entry22 = gtk_entry_new ();
  gtk_widget_show (entry22);
  gtk_fixed_put (GTK_FIXED (fixed12), entry22, 112, 72);
  gtk_widget_set_size_request (entry22, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry22), 8226);

  button44 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button44);
  gtk_fixed_put (GTK_FIXED (fixed12), button44, 288, 72);
  gtk_widget_set_size_request (button44, 104, 24);

  treeview6 = gtk_tree_view_new ();
  gtk_widget_show (treeview6);
  gtk_fixed_put (GTK_FIXED (fixed12), treeview6, 64, 112);
  gtk_widget_set_size_request (treeview6, 288, 96);

  entry23 = gtk_entry_new ();
  gtk_widget_show (entry23);
  gtk_fixed_put (GTK_FIXED (fixed12), entry23, 120, 224);
  gtk_widget_set_size_request (entry23, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry23), 8226);

  label65 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed12), label65, 32, 224);
  gtk_widget_set_size_request (label65, 80, 24);

  label66 = gtk_label_new (_("Type:"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed12), label66, 40, 264);
  gtk_widget_set_size_request (label66, 72, 24);

  comboboxentry18 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry18);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry18, 120, 264);
  gtk_widget_set_size_request (comboboxentry18, 165, 29);

  spinbutton10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton10, 112, 304);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton11, 168, 304);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton12, 224, 304);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  label67 = gtk_label_new (_("Date:"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed12), label67, 48, 304);
  gtk_widget_set_size_request (label67, 56, 24);

  label68 = gtk_label_new (_("Heure:"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed12), label68, 48, 336);
  gtk_widget_set_size_request (label68, 56, 24);

  spinbutton13_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton13, 136, 336);
  gtk_widget_set_size_request (spinbutton13, 56, 24);

  label69 = gtk_label_new (_(":"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed12), label69, 184, 336);
  gtk_widget_set_size_request (label69, 40, 24);

  spinbutton14_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton14, 216, 336);
  gtk_widget_set_size_request (spinbutton14, 60, 27);

  label70 = gtk_label_new (_("Lieu:"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed12), label70, 40, 376);
  gtk_widget_set_size_request (label70, 72, 24);

  comboboxentry19 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry19);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry19, 120, 376);
  gtk_widget_set_size_request (comboboxentry19, 168, 24);

  label71 = gtk_label_new (_("Place:"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed12), label71, 48, 408);
  gtk_widget_set_size_request (label71, 56, 24);

  label72 = gtk_label_new (_("Description:"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed12), label72, 16, 448);
  gtk_widget_set_size_request (label72, 104, 24);

  entry24 = gtk_entry_new ();
  gtk_widget_show (entry24);
  gtk_fixed_put (GTK_FIXED (fixed12), entry24, 128, 448);
  gtk_widget_set_size_request (entry24, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry24), 8226);

  comboboxentry20 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry20);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry20, 120, 408);
  gtk_widget_set_size_request (comboboxentry20, 165, 29);

  button47 = gtk_button_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (button47);
  gtk_fixed_put (GTK_FIXED (fixed12), button47, 320, 488);
  gtk_widget_set_size_request (button47, 96, 32);

  button46 = gtk_button_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (button46);
  gtk_fixed_put (GTK_FIXED (fixed12), button46, 208, 488);
  gtk_widget_set_size_request (button46, 80, 32);

  button45 = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (button45);
  gtk_fixed_put (GTK_FIXED (fixed12), button45, 96, 488);
  gtk_widget_set_size_request (button45, 80, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_des_evenements_Admin, Gestion_des_evenements_Admin, "Gestion_des_evenements_Admin");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label63, "label63");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label64, "label64");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, entry22, "entry22");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, button44, "button44");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, treeview6, "treeview6");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, entry23, "entry23");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label65, "label65");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label66, "label66");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, comboboxentry18, "comboboxentry18");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label67, "label67");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label68, "label68");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label69, "label69");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label70, "label70");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, comboboxentry19, "comboboxentry19");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label71, "label71");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, label72, "label72");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, entry24, "entry24");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, comboboxentry20, "comboboxentry20");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, button47, "button47");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, button46, "button46");
  GLADE_HOOKUP_OBJECT (Gestion_des_evenements_Admin, button45, "button45");

  return Gestion_des_evenements_Admin;
}

GtkWidget*
create_Espace_entraineur_entraineur (void)
{
  GtkWidget *Espace_entraineur_entraineur;
  GtkWidget *fixed13;
  GtkWidget *label78;
  GtkWidget *label79;
  GtkWidget *comboboxentry22;
  GtkWidget *button48;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *vseparator1;
  GtkWidget *label83;
  GtkObject *spinbutton18_adj;
  GtkWidget *spinbutton18;
  GtkObject *spinbutton19_adj;
  GtkWidget *spinbutton19;
  GtkWidget *label86;
  GtkWidget *label84;
  GtkObject *spinbutton20_adj;
  GtkWidget *spinbutton20;
  GtkWidget *label87;
  GtkObject *spinbutton21_adj;
  GtkWidget *spinbutton21;
  GtkWidget *label85;
  GtkWidget *entry28;
  GtkWidget *Rejoindre;
  GtkWidget *label82;
  GtkWidget *comboboxentry24;
  GtkWidget *comboboxentry23;
  GtkWidget *label81;
  GtkWidget *label80;

  Espace_entraineur_entraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Espace_entraineur_entraineur), _("window12"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (Espace_entraineur_entraineur), fixed13);

  label78 = gtk_label_new (_("Rejoindre un Cours"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed13), label78, 104, 32);
  gtk_widget_set_size_request (label78, 176, 32);

  label79 = gtk_label_new (_("Cours:"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed13), label79, 32, 96);
  gtk_widget_set_size_request (label79, 49, 17);

  comboboxentry22 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry22);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry22, 88, 96);
  gtk_widget_set_size_request (comboboxentry22, 157, 21);

  button48 = gtk_button_new_with_mnemonic (_("Voir"));
  gtk_widget_show (button48);
  gtk_fixed_put (GTK_FIXED (fixed13), button48, 248, 96);
  gtk_widget_set_size_request (button48, 72, 24);

  spinbutton15_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton15, 48, 136);
  gtk_widget_set_size_request (spinbutton15, 52, 19);

  spinbutton16_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton16, 96, 136);
  gtk_widget_set_size_request (spinbutton16, 44, 19);

  spinbutton17_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton17, 136, 136);
  gtk_widget_set_size_request (spinbutton17, 44, 19);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed13), vseparator1, 192, 128);
  gtk_widget_set_size_request (vseparator1, 16, 120);

  label83 = gtk_label_new (_("Horaires:"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed13), label83, 200, 136);
  gtk_widget_set_size_request (label83, 80, 16);

  spinbutton18_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton18 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton18_adj), 1, 0);
  gtk_widget_show (spinbutton18);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton18, 272, 136);
  gtk_widget_set_size_request (spinbutton18, 48, 24);

  spinbutton19_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton19 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton19_adj), 1, 0);
  gtk_widget_show (spinbutton19);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton19, 336, 136);
  gtk_widget_set_size_request (spinbutton19, 48, 24);

  label86 = gtk_label_new (_(":"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (fixed13), label86, 312, 136);
  gtk_widget_set_size_request (label86, 32, 17);

  label84 = gtk_label_new (_("Places:"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed13), label84, 208, 168);
  gtk_widget_set_size_request (label84, 56, 16);

  spinbutton20_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton20 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton20_adj), 1, 0);
  gtk_widget_show (spinbutton20);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton20, 264, 168);
  gtk_widget_set_size_request (spinbutton20, 48, 24);

  label87 = gtk_label_new (_("/"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed13), label87, 312, 168);
  gtk_widget_set_size_request (label87, 40, 24);

  spinbutton21_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton21 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton21_adj), 1, 0);
  gtk_widget_show (spinbutton21);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton21, 344, 168);
  gtk_widget_set_size_request (spinbutton21, 48, 24);

  label85 = gtk_label_new (_("Duree:"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed13), label85, 208, 200);
  gtk_widget_set_size_request (label85, 57, 17);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed13), entry28, 264, 200);
  gtk_widget_set_size_request (entry28, 128, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  Rejoindre = gtk_button_new_with_mnemonic (_("Rejoindre"));
  gtk_widget_show (Rejoindre);
  gtk_fixed_put (GTK_FIXED (fixed13), Rejoindre, 144, 248);
  gtk_widget_set_size_request (Rejoindre, 104, 37);

  label82 = gtk_label_new (_("Type:"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed13), label82, 0, 192);
  gtk_widget_set_size_request (label82, 48, 24);

  comboboxentry24 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry24);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry24, 48, 192);
  gtk_widget_set_size_request (comboboxentry24, 125, 21);

  comboboxentry23 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry23);
  gtk_fixed_put (GTK_FIXED (fixed13), comboboxentry23, 48, 160);
  gtk_widget_set_size_request (comboboxentry23, 125, 21);

  label81 = gtk_label_new (_("Salle:"));
  gtk_widget_show (label81);
  gtk_fixed_put (GTK_FIXED (fixed13), label81, 0, 160);
  gtk_widget_set_size_request (label81, 48, 24);

  label80 = gtk_label_new (_("Date:"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed13), label80, 0, 136);
  gtk_widget_set_size_request (label80, 56, 16);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Espace_entraineur_entraineur, Espace_entraineur_entraineur, "Espace_entraineur_entraineur");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label78, "label78");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label79, "label79");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, comboboxentry22, "comboboxentry22");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, button48, "button48");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label83, "label83");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton18, "spinbutton18");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton19, "spinbutton19");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label86, "label86");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label84, "label84");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton20, "spinbutton20");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label87, "label87");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, spinbutton21, "spinbutton21");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label85, "label85");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, Rejoindre, "Rejoindre");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label82, "label82");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, comboboxentry24, "comboboxentry24");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, comboboxentry23, "comboboxentry23");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label81, "label81");
  GLADE_HOOKUP_OBJECT (Espace_entraineur_entraineur, label80, "label80");

  return Espace_entraineur_entraineur;
}

GtkWidget*
create_Cours_sportifs__membre (void)
{
  GtkWidget *Cours_sportifs__membre;
  GtkWidget *fixed14;
  GtkWidget *label88;
  GtkWidget *label89;
  GtkWidget *comboboxentry25;
  GtkWidget *button50;
  GtkObject *spinbutton22_adj;
  GtkWidget *spinbutton22;
  GtkObject *spinbutton23_adj;
  GtkWidget *spinbutton23;
  GtkObject *spinbutton24_adj;
  GtkWidget *spinbutton24;
  GtkWidget *label90;
  GtkWidget *label91;
  GtkWidget *comboboxentry26;
  GtkWidget *label92;
  GtkWidget *comboboxentry27;
  GtkObject *spinbutton25_adj;
  GtkWidget *spinbutton25;
  GtkWidget *label93;
  GtkObject *spinbutton26_adj;
  GtkWidget *spinbutton26;
  GtkObject *spinbutton27_adj;
  GtkWidget *spinbutton27;
  GtkWidget *label94;
  GtkWidget *label95;
  GtkObject *spinbutton28_adj;
  GtkWidget *spinbutton28;
  GtkWidget *label96;
  GtkWidget *entry29;
  GtkWidget *button51;

  Cours_sportifs__membre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Cours_sportifs__membre), _("window13"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (Cours_sportifs__membre), fixed14);

  label88 = gtk_label_new (_("Cours Disponibles"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed14), label88, 136, 24);
  gtk_widget_set_size_request (label88, 144, 40);

  label89 = gtk_label_new (_("Cours:"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed14), label89, 8, 80);
  gtk_widget_set_size_request (label89, 73, 24);

  comboboxentry25 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry25);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxentry25, 72, 80);
  gtk_widget_set_size_request (comboboxentry25, 189, 24);

  button50 = gtk_button_new_with_mnemonic (_("Voir"));
  gtk_widget_show (button50);
  gtk_fixed_put (GTK_FIXED (fixed14), button50, 272, 80);
  gtk_widget_set_size_request (button50, 74, 29);

  spinbutton22_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton22 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton22_adj), 1, 0);
  gtk_widget_show (spinbutton22);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton22, 72, 120);
  gtk_widget_set_size_request (spinbutton22, 56, 24);

  spinbutton23_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton23 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton23_adj), 1, 0);
  gtk_widget_show (spinbutton23);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton23, 128, 120);
  gtk_widget_set_size_request (spinbutton23, 56, 24);

  spinbutton24_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton24 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton24_adj), 1, 0);
  gtk_widget_show (spinbutton24);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton24, 192, 120);
  gtk_widget_set_size_request (spinbutton24, 64, 24);

  label90 = gtk_label_new (_("Date:"));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed14), label90, 16, 120);
  gtk_widget_set_size_request (label90, 64, 24);

  label91 = gtk_label_new (_("Salle:"));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed14), label91, 24, 160);
  gtk_widget_set_size_request (label91, 49, 17);

  comboboxentry26 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry26);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxentry26, 72, 160);
  gtk_widget_set_size_request (comboboxentry26, 181, 21);

  label92 = gtk_label_new (_("Coach:"));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed14), label92, 16, 192);
  gtk_widget_set_size_request (label92, 56, 24);

  comboboxentry27 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry27);
  gtk_fixed_put (GTK_FIXED (fixed14), comboboxentry27, 72, 192);
  gtk_widget_set_size_request (comboboxentry27, 181, 24);

  spinbutton25_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton25 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton25_adj), 1, 0);
  gtk_widget_show (spinbutton25);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton25, 80, 224);
  gtk_widget_set_size_request (spinbutton25, 60, 27);

  label93 = gtk_label_new (_("Horaire:"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed14), label93, 16, 224);
  gtk_widget_set_size_request (label93, 56, 24);

  spinbutton26_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton26 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton26_adj), 1, 0);
  gtk_widget_show (spinbutton26);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton26, 144, 224);
  gtk_widget_set_size_request (spinbutton26, 60, 27);

  spinbutton27_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton27 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton27_adj), 1, 0);
  gtk_widget_show (spinbutton27);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton27, 80, 256);
  gtk_widget_set_size_request (spinbutton27, 48, 27);

  label94 = gtk_label_new (_("Places:"));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed14), label94, 16, 256);
  gtk_widget_set_size_request (label94, 56, 24);

  label95 = gtk_label_new (_("/"));
  gtk_widget_show (label95);
  gtk_fixed_put (GTK_FIXED (fixed14), label95, 128, 256);
  gtk_widget_set_size_request (label95, 48, 25);

  spinbutton28_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton28 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton28_adj), 1, 0);
  gtk_widget_show (spinbutton28);
  gtk_fixed_put (GTK_FIXED (fixed14), spinbutton28, 160, 256);
  gtk_widget_set_size_request (spinbutton28, 48, 24);

  label96 = gtk_label_new (_("Duree:"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed14), label96, 16, 288);
  gtk_widget_set_size_request (label96, 56, 24);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed14), entry29, 72, 288);
  gtk_widget_set_size_request (entry29, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  button51 = gtk_button_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (button51);
  gtk_fixed_put (GTK_FIXED (fixed14), button51, 136, 320);
  gtk_widget_set_size_request (button51, 122, 37);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Cours_sportifs__membre, Cours_sportifs__membre, "Cours_sportifs__membre");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label88, "label88");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label89, "label89");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, comboboxentry25, "comboboxentry25");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, button50, "button50");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton22, "spinbutton22");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton23, "spinbutton23");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton24, "spinbutton24");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label90, "label90");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label91, "label91");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, comboboxentry26, "comboboxentry26");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label92, "label92");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, comboboxentry27, "comboboxentry27");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton25, "spinbutton25");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label93, "label93");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton26, "spinbutton26");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton27, "spinbutton27");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label94, "label94");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label95, "label95");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, spinbutton28, "spinbutton28");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, label96, "label96");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (Cours_sportifs__membre, button51, "button51");

  return Cours_sportifs__membre;
}

GtkWidget*
create_Equippements_entraineurs (void)
{
  GtkWidget *Equippements_entraineurs;
  GtkWidget *fixed15;
  GtkWidget *label97;
  GtkWidget *button52;
  GtkWidget *comboboxentry29;
  GtkWidget *comboboxentry28;
  GtkWidget *label98;
  GtkWidget *label99;
  GtkObject *spinbutton29_adj;
  GtkWidget *spinbutton29;
  GtkWidget *label100;
  GtkObject *spinbutton30_adj;
  GtkWidget *spinbutton30;
  GtkObject *spinbutton31_adj;
  GtkWidget *spinbutton31;
  GtkObject *spinbutton32_adj;
  GtkWidget *spinbutton32;
  GtkWidget *label101;
  GtkWidget *button53;

  Equippements_entraineurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Equippements_entraineurs), _("window14"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (Equippements_entraineurs), fixed15);

  label97 = gtk_label_new (_("Reservation equipements"));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed15), label97, 80, 32);
  gtk_widget_set_size_request (label97, 208, 40);

  button52 = gtk_button_new_with_mnemonic (_("Voir"));
  gtk_widget_show (button52);
  gtk_fixed_put (GTK_FIXED (fixed15), button52, 280, 88);
  gtk_widget_set_size_request (button52, 74, 29);

  comboboxentry29 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry29);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxentry29, 120, 136);
  gtk_widget_set_size_request (comboboxentry29, 189, 29);

  comboboxentry28 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry28);
  gtk_fixed_put (GTK_FIXED (fixed15), comboboxentry28, 80, 88);
  gtk_widget_set_size_request (comboboxentry28, 189, 29);

  label98 = gtk_label_new (_("Cours:"));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed15), label98, 8, 88);
  gtk_widget_set_size_request (label98, 80, 24);

  label99 = gtk_label_new (_("Equipements:"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed15), label99, 0, 136);
  gtk_widget_set_size_request (label99, 120, 24);

  spinbutton29_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton29 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton29_adj), 1, 0);
  gtk_widget_show (spinbutton29);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton29, 120, 176);
  gtk_widget_set_size_request (spinbutton29, 60, 27);

  label100 = gtk_label_new (_("Quantite:"));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed15), label100, 16, 176);
  gtk_widget_set_size_request (label100, 88, 24);

  spinbutton30_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton30 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton30_adj), 1, 0);
  gtk_widget_show (spinbutton30);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton30, 120, 208);
  gtk_widget_set_size_request (spinbutton30, 60, 27);

  spinbutton31_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton31 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton31_adj), 1, 0);
  gtk_widget_show (spinbutton31);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton31, 184, 208);
  gtk_widget_set_size_request (spinbutton31, 60, 27);

  spinbutton32_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton32 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton32_adj), 1, 0);
  gtk_widget_show (spinbutton32);
  gtk_fixed_put (GTK_FIXED (fixed15), spinbutton32, 248, 208);
  gtk_widget_set_size_request (spinbutton32, 60, 27);

  label101 = gtk_label_new (_("Date:"));
  gtk_widget_show (label101);
  gtk_fixed_put (GTK_FIXED (fixed15), label101, 24, 208);
  gtk_widget_set_size_request (label101, 73, 24);

  button53 = gtk_button_new_with_mnemonic (_("Reserver"));
  gtk_widget_show (button53);
  gtk_fixed_put (GTK_FIXED (fixed15), button53, 152, 256);
  gtk_widget_set_size_request (button53, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Equippements_entraineurs, Equippements_entraineurs, "Equippements_entraineurs");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, label97, "label97");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, button52, "button52");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, comboboxentry29, "comboboxentry29");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, comboboxentry28, "comboboxentry28");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, label98, "label98");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, label99, "label99");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, spinbutton29, "spinbutton29");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, label100, "label100");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, spinbutton30, "spinbutton30");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, spinbutton31, "spinbutton31");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, spinbutton32, "spinbutton32");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, label101, "label101");
  GLADE_HOOKUP_OBJECT (Equippements_entraineurs, button53, "button53");

  return Equippements_entraineurs;
}

GtkWidget*
create_Centre_entraineurs (void)
{
  GtkWidget *Centre_entraineurs;
  GtkWidget *fixed16;
  GtkWidget *label102;
  GtkWidget *label103;
  GtkWidget *comboboxentry30;
  GtkWidget *button54;
  GtkWidget *label104;
  GtkWidget *entry30;
  GtkWidget *label105;
  GtkObject *spinbutton33_adj;
  GtkWidget *spinbutton33;
  GtkWidget *label106;
  GtkWidget *entry31;
  GtkWidget *button55;

  Centre_entraineurs = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Centre_entraineurs), _("window15"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (Centre_entraineurs), fixed16);

  label102 = gtk_label_new (_("Rejoindre un centre"));
  gtk_widget_show (label102);
  gtk_fixed_put (GTK_FIXED (fixed16), label102, 120, 32);
  gtk_widget_set_size_request (label102, 152, 40);

  label103 = gtk_label_new (_("Centre:"));
  gtk_widget_show (label103);
  gtk_fixed_put (GTK_FIXED (fixed16), label103, 16, 88);
  gtk_widget_set_size_request (label103, 64, 32);

  comboboxentry30 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry30);
  gtk_fixed_put (GTK_FIXED (fixed16), comboboxentry30, 80, 88);
  gtk_widget_set_size_request (comboboxentry30, 189, 29);

  button54 = gtk_button_new_with_mnemonic (_("Voir"));
  gtk_widget_show (button54);
  gtk_fixed_put (GTK_FIXED (fixed16), button54, 288, 88);
  gtk_widget_set_size_request (button54, 74, 29);

  label104 = gtk_label_new (_("Ville:"));
  gtk_widget_show (label104);
  gtk_fixed_put (GTK_FIXED (fixed16), label104, 8, 128);
  gtk_widget_set_size_request (label104, 73, 25);

  entry30 = gtk_entry_new ();
  gtk_widget_show (entry30);
  gtk_fixed_put (GTK_FIXED (fixed16), entry30, 80, 128);
  gtk_widget_set_size_request (entry30, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry30), 8226);

  label105 = gtk_label_new (_("Capacite:"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed16), label105, 8, 168);
  gtk_widget_set_size_request (label105, 80, 24);

  spinbutton33_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton33 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton33_adj), 1, 0);
  gtk_widget_show (spinbutton33);
  gtk_fixed_put (GTK_FIXED (fixed16), spinbutton33, 96, 168);
  gtk_widget_set_size_request (spinbutton33, 60, 27);

  label106 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed16), label106, 8, 208);
  gtk_widget_set_size_request (label106, 88, 24);

  entry31 = gtk_entry_new ();
  gtk_widget_show (entry31);
  gtk_fixed_put (GTK_FIXED (fixed16), entry31, 80, 208);
  gtk_widget_set_size_request (entry31, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry31), 8226);

  button55 = gtk_button_new_with_mnemonic (_("Postuler"));
  gtk_widget_show (button55);
  gtk_fixed_put (GTK_FIXED (fixed16), button55, 128, 248);
  gtk_widget_set_size_request (button55, 136, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Centre_entraineurs, Centre_entraineurs, "Centre_entraineurs");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, label102, "label102");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, label103, "label103");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, comboboxentry30, "comboboxentry30");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, button54, "button54");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, label104, "label104");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, entry30, "entry30");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, label105, "label105");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, spinbutton33, "spinbutton33");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, label106, "label106");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, entry31, "entry31");
  GLADE_HOOKUP_OBJECT (Centre_entraineurs, button55, "button55");

  return Centre_entraineurs;
}

GtkWidget*
create_Evenements_membre (void)
{
  GtkWidget *Evenements_membre;
  GtkWidget *fixed17;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *comboboxentry31;
  GtkWidget *Voir;
  GtkWidget *label109;
  GtkObject *spinbutton34_adj;
  GtkWidget *spinbutton34;
  GtkObject *spinbutton35_adj;
  GtkWidget *spinbutton35;
  GtkObject *spinbutton36_adj;
  GtkWidget *spinbutton36;
  GtkObject *spinbutton37_adj;
  GtkWidget *spinbutton37;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkObject *spinbutton38_adj;
  GtkWidget *spinbutton38;
  GtkWidget *label112;
  GtkWidget *entry32;
  GtkWidget *label113;
  GtkObject *spinbutton39_adj;
  GtkWidget *spinbutton39;
  GtkWidget *label114;
  GtkObject *spinbutton40_adj;
  GtkWidget *spinbutton40;
  GtkWidget *button57;

  Evenements_membre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Evenements_membre), _("window16"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (Evenements_membre), fixed17);

  label107 = gtk_label_new (_("Evenements Dsiponibles"));
  gtk_widget_show (label107);
  gtk_fixed_put (GTK_FIXED (fixed17), label107, 112, 24);
  gtk_widget_set_size_request (label107, 176, 40);

  label108 = gtk_label_new (_("Evenement:"));
  gtk_widget_show (label108);
  gtk_fixed_put (GTK_FIXED (fixed17), label108, 16, 80);
  gtk_widget_set_size_request (label108, 112, 24);

  comboboxentry31 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry31);
  gtk_fixed_put (GTK_FIXED (fixed17), comboboxentry31, 120, 80);
  gtk_widget_set_size_request (comboboxentry31, 189, 29);

  Voir = gtk_button_new_with_mnemonic (_("Voir"));
  gtk_widget_show (Voir);
  gtk_fixed_put (GTK_FIXED (fixed17), Voir, 320, 80);
  gtk_widget_set_size_request (Voir, 74, 29);

  label109 = gtk_label_new (_("Date:"));
  gtk_widget_show (label109);
  gtk_fixed_put (GTK_FIXED (fixed17), label109, 32, 120);
  gtk_widget_set_size_request (label109, 81, 24);

  spinbutton34_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton34 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton34_adj), 1, 0);
  gtk_widget_show (spinbutton34);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton34, 120, 120);
  gtk_widget_set_size_request (spinbutton34, 60, 27);

  spinbutton35_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton35 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton35_adj), 1, 0);
  gtk_widget_show (spinbutton35);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton35, 184, 120);
  gtk_widget_set_size_request (spinbutton35, 60, 27);

  spinbutton36_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton36 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton36_adj), 1, 0);
  gtk_widget_show (spinbutton36);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton36, 248, 120);
  gtk_widget_set_size_request (spinbutton36, 60, 27);

  spinbutton37_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton37 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton37_adj), 1, 0);
  gtk_widget_show (spinbutton37);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton37, 128, 160);
  gtk_widget_set_size_request (spinbutton37, 60, 27);

  label110 = gtk_label_new (_("Heures:"));
  gtk_widget_show (label110);
  gtk_fixed_put (GTK_FIXED (fixed17), label110, 32, 160);
  gtk_widget_set_size_request (label110, 89, 25);

  label111 = gtk_label_new (_(":"));
  gtk_widget_show (label111);
  gtk_fixed_put (GTK_FIXED (fixed17), label111, 176, 160);
  gtk_widget_set_size_request (label111, 48, 32);

  spinbutton38_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton38 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton38_adj), 1, 0);
  gtk_widget_show (spinbutton38);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton38, 208, 160);
  gtk_widget_set_size_request (spinbutton38, 60, 27);

  label112 = gtk_label_new (_("Lieu:"));
  gtk_widget_show (label112);
  gtk_fixed_put (GTK_FIXED (fixed17), label112, 40, 200);
  gtk_widget_set_size_request (label112, 73, 24);

  entry32 = gtk_entry_new ();
  gtk_widget_show (entry32);
  gtk_fixed_put (GTK_FIXED (fixed17), entry32, 128, 200);
  gtk_widget_set_size_request (entry32, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry32), 8226);

  label113 = gtk_label_new (_("Places:"));
  gtk_widget_show (label113);
  gtk_fixed_put (GTK_FIXED (fixed17), label113, 48, 240);
  gtk_widget_set_size_request (label113, 72, 24);

  spinbutton39_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton39 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton39_adj), 1, 0);
  gtk_widget_show (spinbutton39);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton39, 136, 240);
  gtk_widget_set_size_request (spinbutton39, 60, 27);

  label114 = gtk_label_new (_("/"));
  gtk_widget_show (label114);
  gtk_fixed_put (GTK_FIXED (fixed17), label114, 184, 232);
  gtk_widget_set_size_request (label114, 56, 40);

  spinbutton40_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton40 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton40_adj), 1, 0);
  gtk_widget_show (spinbutton40);
  gtk_fixed_put (GTK_FIXED (fixed17), spinbutton40, 224, 240);
  gtk_widget_set_size_request (spinbutton40, 60, 27);

  button57 = gtk_button_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (button57);
  gtk_fixed_put (GTK_FIXED (fixed17), button57, 160, 280);
  gtk_widget_set_size_request (button57, 104, 32);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Evenements_membre, Evenements_membre, "Evenements_membre");
  GLADE_HOOKUP_OBJECT (Evenements_membre, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label107, "label107");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label108, "label108");
  GLADE_HOOKUP_OBJECT (Evenements_membre, comboboxentry31, "comboboxentry31");
  GLADE_HOOKUP_OBJECT (Evenements_membre, Voir, "Voir");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label109, "label109");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton34, "spinbutton34");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton35, "spinbutton35");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton36, "spinbutton36");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton37, "spinbutton37");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label110, "label110");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label111, "label111");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton38, "spinbutton38");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label112, "label112");
  GLADE_HOOKUP_OBJECT (Evenements_membre, entry32, "entry32");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label113, "label113");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton39, "spinbutton39");
  GLADE_HOOKUP_OBJECT (Evenements_membre, label114, "label114");
  GLADE_HOOKUP_OBJECT (Evenements_membre, spinbutton40, "spinbutton40");
  GLADE_HOOKUP_OBJECT (Evenements_membre, button57, "button57");

  return Evenements_membre;
}

