/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_choix (void);
GtkWidget* create_window_signup (void);
GtkWidget* create_window_login (void);
GtkWidget* create_DashAdmin (void);
GtkWidget* create_DAshMembre (void);
GtkWidget* create_DashEntraineur (void);
GtkWidget* create_Gestion_des_equippements_Admin (void);
GtkWidget* create_Equippements_entraineurs (void);
GtkWidget* create_Gestion_entraineurs_Admin (void);
GtkWidget* create_Espace_entraineur_entraineur (void);
