/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *login;
  GtkWidget *Dash_Admin;
  GtkWidget *Dash_Membre;
  GtkWidget *Dash_Entraineur;
  GtkWidget *Gestion_membre_Admin;
  GtkWidget *Gestion_Membre_Membre;
  GtkWidget *Gestion_entraineurs_Admin;
  GtkWidget *Gestions_des_Cours_sportifs_Admin;
  GtkWidget *Gestion_des_equippements_Admin;
  GtkWidget *Gestion_des_Centres_Sportifs_Admin;
  GtkWidget *Gestion_des_evenements_Admin;
  GtkWidget *Espace_entraineur_entraineur;
  GtkWidget *Cours_sportifs__membre;
  GtkWidget *Equippements_entraineurs;
  GtkWidget *Centre_entraineurs;
  GtkWidget *Evenements_membre;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  login = create_login ();
  gtk_widget_show (login);
  Dash_Admin = create_Dash_Admin ();
  gtk_widget_show (Dash_Admin);
  Dash_Membre = create_Dash_Membre ();
  gtk_widget_show (Dash_Membre);
  Dash_Entraineur = create_Dash_Entraineur ();
  gtk_widget_show (Dash_Entraineur);
  Gestion_membre_Admin = create_Gestion_membre_Admin ();
  gtk_widget_show (Gestion_membre_Admin);
  Gestion_Membre_Membre = create_Gestion_Membre_Membre ();
  gtk_widget_show (Gestion_Membre_Membre);
  Gestion_entraineurs_Admin = create_Gestion_entraineurs_Admin ();
  gtk_widget_show (Gestion_entraineurs_Admin);
  Gestions_des_Cours_sportifs_Admin = create_Gestions_des_Cours_sportifs_Admin ();
  gtk_widget_show (Gestions_des_Cours_sportifs_Admin);
  Gestion_des_equippements_Admin = create_Gestion_des_equippements_Admin ();
  gtk_widget_show (Gestion_des_equippements_Admin);
  Gestion_des_Centres_Sportifs_Admin = create_Gestion_des_Centres_Sportifs_Admin ();
  gtk_widget_show (Gestion_des_Centres_Sportifs_Admin);
  Gestion_des_evenements_Admin = create_Gestion_des_evenements_Admin ();
  gtk_widget_show (Gestion_des_evenements_Admin);
  Espace_entraineur_entraineur = create_Espace_entraineur_entraineur ();
  gtk_widget_show (Espace_entraineur_entraineur);
  Cours_sportifs__membre = create_Cours_sportifs__membre ();
  gtk_widget_show (Cours_sportifs__membre);
  Equippements_entraineurs = create_Equippements_entraineurs ();
  gtk_widget_show (Equippements_entraineurs);
  Centre_entraineurs = create_Centre_entraineurs ();
  gtk_widget_show (Centre_entraineurs);
  Evenements_membre = create_Evenements_membre ();
  gtk_widget_show (Evenements_membre);

  gtk_main ();
  return 0;
}

